default: &default
  adapter: postgresql
  encoding: utf-8
  reconnect: false
  pool: 5
  timeout: 5000
  host: localhost
  username: "postgres"
  password: "password"

development:
  <<: *default
  database: formidable_development

test:
  <<: *default
  database: formidable_test

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
